### PR TITLE
fix: comboBox does not show noOptionsMessage when there are no options

### PR DESCRIPTION
**Pull request by cybertron288**
## What does it do?
This PR fixes when there are no options available in ComboBox then noOptionsMessage should show #1626 

## Why is it needed?
when there are no options in basic combobox it shows small bar. instead it should display `noOptionsMessage`

## How to test it?
in combobox storybook code, comment or remove all ComboboxOption of Basic combobox, it should display **No Fruit(s) found** 
Screenshot 2024-06-13 at 9 09 20 PM

## Related issue(s)/PR(s)
The related issue is mentioned here: #1626

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
instead of changing a story, i would probably expect a test to accompany this PR :)

**Comment by cybertron288** [comment]
> instead of changing a story, i would probably expect a test to accompany this PR :)

sure, I'll do that.

**Comment by cybertron288** [comment]
Hi @joshuaellis, I have made the changes as requested. pls review this.

**Comment by madhurisandbhor** [comment]
you have many unexpected changes in PR, please keep the necessary changes only, thanks

**Comment by cybertron288** [comment]
Hi @madhurisandbhor, I have created new PR for the fix you can find it here: [PR Link]( https://github.com/strapi/design-system/pull/1762), please review this and close this PR. let me know if any changes are required.

**Pull request closed without merging**
