### PR TITLE
fix: comboBox does not show noOptionsMessage when there are no options

### PR DESCRIPTION
**Pull request by cybertron288**
## What does it do?
This PR fixes when there are no options available in ComboBox then noOptionsMessage should show #1626 

## Why is it needed?
when there are no options in basic combobox it shows small bar. instead it should display `noOptionsMessage`

## How to test it?
in combobox storybook code, comment or remove all ComboboxOption of Basic combobox, it should display **No Fruit(s) found** 
Screenshot 2024-06-13 at 9 09 20 PM

## Related issue(s)/PR(s)
The related issue is mentioned here: #1626

### CODE REVIEW

**Comment by cybertron288** [comment]
Hi @madhurisandbhor, will make it open once I update the storybook.

**Comment by cybertron288** [comment]
Hi @madhurisandbhor, added docs and updated storybook, let me know anything else is required.

**Comment by madhurisandbhor** [comment]
It would be great if you add unit test instead of story to show `no options`, its not really adding any meaning to show it as a story. Also please add a changeset as suggested [here](https://github.com/strapi/design-system/pull/1762#issuecomment-2245999416)

**Comment by madhurisandbhor** [comment]
fixed by https://github.com/strapi/design-system/pull/1770

**Pull request closed without merging**
