### PR TITLE
Fix simple menu click and fix some stories props

### PR DESCRIPTION
**Pull request by HichamELBSI**
### What does it do?

Prevent default on mouse down event of the SimpleMenu component.

### Why is it needed?

Prevent a bug on React 18.

### How to test it?

Should work the same way

### CODE REVIEW

**Review by gu-stav — APPROVED** [review]
Looks good to me. Thanks!

**Comment by gu-stav** [comment]
@HichamELBSI Does this need to be done on the `v2` version of the `SimpleMenu` too?

**Comment by HichamELBSI** [comment]
> @HichamELBSI Does this need to be done on the `v2` version of the `SimpleMenu` too?

Yes, nice catch!

**Review by gu-stav — APPROVED** [review]
✨

**Pull request merged**
