### PR TITLE
fix text input font to be inherited

### PR DESCRIPTION
**Pull request by Zoha**
### What does it do?

applies our custom fonts styles on TextInput components
fixes: #605 

### Why is it needed?

we need to apply page font styles on text inputs 

### How to test it?

check the related issue 

### Related issue(s)/PR(s)

#605 

### screenshots

before this pr : 

screenshot from applied font after to text input after inheriting style

### CODE REVIEW

**Review by HichamELBSI — CHANGES_REQUESTED** [review]
Awesome thanks you. Can you make sure to update the storyshots please?

```js
yarn test --updateSnapshot
```

**Comment by Zoha** [comment]
@HichamELBSI thanks for your notice, I updated the snapshots
but my tests are failing on main that's why I didn't update them
now everything is ok 😉

**Comment by HichamELBSI** [comment]
Awesome thank you @Zoha

**Comment by HichamELBSI** [comment]
Something is wrong with the storyshots as you can see on the CI test workflow. Can you make sure everything is ok please 😅 ?

**Comment by Zoha** [comment]
@HichamELBSI 
oh. I am using windows so that would make different snapshots 😃 
also this is why I was getting test failures on the main branch ( on my windows )
I updated the snapshots using Docker VM 
and the test is passed on my fork repo  and VM
I think we should be ok 👍 
note: newly created snapshot is not different from the main branch

**Comment by HichamELBSI** [comment]
Can you update your branch please 🙏🏽

**Comment by Zoha** [comment]
@HichamELBSI updated 😉

**Review by HichamELBSI — APPROVED** [review]
Looks good to me 👍🏽

**Comment by HichamELBSI** [comment]
Good job @Zoha

**Comment by Zoha** [comment]
thanks @HichamELBSI  👍

**Pull request merged**
