### PR TITLE
Flex Component: Add `gap` prop

### PR DESCRIPTION
**Pull request by MattieBelt**
# Add `gap` prop to Flex Component

## Description
Use theme spaces to set the flex property `gap` on your Flex component.

## Demo
Example on : https://design-system-7r256h8ex-strapijs.vercel.app/?path=/story/design-system-technical-components-flex--base

## API

```jsx
<Flex gap={2}>
  <IconButton label="Edit" icon={<Pencil />} />
  <IconButton label="Create" icon={<Plus />} />
  <IconButton label="Delete" icon={<Trash />} />
  <IconButton label="Publish" icon={<Play />} />
</Flex>
```

### Discussion
- Should `gap` also allow responsive properties just like the padding props in the Box component?

### CODE REVIEW

**Comment by gu-stav** [comment]
Thanks also for this PR. I really like it, but need to confirm `gap` is within our browser support matrix (not sure about IE11): https://caniuse.com/flexbox-gap

**Comment by ronronscelestes** [comment]
Thank you, flex gap would be great!
I wonder though if we couldn't use `strapi-design-system/src/helpers/handleResponsiveValues.js` helper to allow responsive values + possibility to custom column / row gap? 

image

Our Grid component already does this, it allows:
```
gap={4}
gap={{ desktop: 5, tablet: 2, mobile: 1 }}
gap="10px 20px"
```

WDYT?

**Comment by MattieBelt** [comment]
> Thank you, flex gap would be great! I wonder though if we couldn't use `strapi-design-system/src/helpers/handleResponsiveValues.js` helper to allow responsive values + possibility to custom column / row gap?
> 
> image
> 
> Our Grid component already does this, it allows:
> 
> ```
> gap={4}
> gap={{ desktop: 5, tablet: 2, mobile: 1 }}
> gap="10px 20px"
> ```
> 
> WDYT?


I was thinking the same 😉☝🏼 
> Discussion
Should gap also allow responsive properties just like the padding props in the Box component?

**Review by HichamELBSI — APPROVED** [review]
Hi @MattieBelt, thanks for the contribution 😄

**Comment by ronronscelestes** [comment]
Not sure why but I had to "Approve and run" for the tests to run.
Should be good now - just need to wait for the tests to pass!

**Comment by HichamELBSI** [comment]
@MattieBelt You'll need to update the storyshots.
```
cd packages/strapi-design-system
yarn test -u
```

**Review by HichamELBSI — APPROVED** [review]
LGTM

**Pull request merged**
