### PR TITLE
add google tag manager

### PR DESCRIPTION
**Pull request by Bassel17**
# Add google tag manager

## Description
Added google tag manager and cookie bot

## Demo
Example on: https://design-system-website-git-add-google-analytics-strapijs.vercel.app/

### CODE REVIEW

**Review by gu-stav — CHANGES_REQUESTED** [review]
I've tested in two browsers (Chrome + FF) and in both cases cookiebot tries to access a file which shows a 404. GTM is loaded though.

**Comment by Bassel17** [comment]
@gu-stav I suppose it shouldn't work, this domain is not added to cookie bot

**Review by gu-stav — APPROVED** [review]
Alright, I believe you 🌻

**Comment by gu-stav** [comment]
@Bassel17 The configuration fetch still fails in production: https://consentcdn.cookiebot.com/consentconfig/609a66e2-0531-441d-b473-6cbd335dd21e/design-system.strapi.io/configuration.js

**Pull request merged**
