### PR TITLE
fix: multiple UI styling changes

### PR DESCRIPTION
**Pull request by madhurisandbhor**
### What does it do?

1. Field label style fixed
2. Tertiary Icon button `color: neutral500` and `hover-color: neutral600` updated as per design
3. Simple menu with `tag: IconButton` should have `tertiary` style applied
4. Select carret down `color: neutral500` fixed.
5. Combobox with no options provided should show default "No results found" value.

### Related issue(s)/PR(s)

Fixes: https://github.com/strapi/design-system/issues/1626

### CODE REVIEW

**Comment by madhurisandbhor** [comment]
@lucasboilly Could you please check deployment link for changes: https://design-system-3lcbqtedh-strapijs.vercel.app/?path=/docs/getting-started-welcome--docs

**Comment by lucasboilly** [comment]
@madhurisandbhor could you add a 4px spacing above the popover for all variants in the SimpleMenu? Except that, all changes of this PR look good 👍

CleanShot 2024-08-06 at 11 43 48@2x

**Review by remidej — COMMENTED** [review]
Code changes LGTM 👍 i let Lucas do the testing

**Comment by madhurisandbhor** [comment]
@lucasboilly @remidej could you please provide your approvals if its good for you, thanks!

**Review by remidej — APPROVED** [review]

**Pull request merged**
