### PR TITLE
fix: button icons position and width

### PR DESCRIPTION
**Pull request by HichamELBSI**
### What does it do?

Fix the alignment of the start and end icons.

### Why is it needed?

Describe the issue you are solving.

### How to test it?

Provide information about the environment and the path to verify the behaviour.

### Related issue(s)/PR(s)

https://github.com/strapi/strapi/issues/20986

### CODE REVIEW

**Review by alexandrebodin — COMMENTED** [review]
Thanks for the PR. Aren't we missing a margin right & left for start & end icons now ?

**Comment by HichamELBSI** [comment]
> Thanks for the PR. Aren't we missing a margin right & left for start & end icons now ?

If this fix is what we wanted to do visually @lucasboilly, there is no need to add a margin, there is a 8px gap between icons and the text. Now that the text is taking 100% of the remaining space, the text will be centered by default. I don't understand why there was a flex 1 on the icons (cc: @simotae14 @remidej if you have any context about it 🤷🏽‍♂️ ) ⬇️ Screenshots of the use cases with the new update.

Start icon - normal size
Screenshot 2024-08-29 at 11 13 10

Start icon - fullwidth (which is used in the CM list view filters)
Screenshot 2024-08-29 at 11 13 06

End icon - normal size
Screenshot 2024-08-29 at 11 15 25
Screenshot 2024-08-29 at 11 15 30

Start + End icon
Screenshot 2024-08-29 at 11 12 52
Screenshot 2024-08-29 at 11 12 58

**Comment by HichamELBSI** [comment]
> From @lucasboilly comment here https://www.notion.so/strapi/The-button-in-the-filters-of-the-list-view-is-broken-029d9bac6fa64046ae56782fce9496c0?d=7eb956cf8eea434199d2dfcf6483ca65 I think we are expecting the icon to always be attached to the text even in fullwidth so I think we have to remove the flex & not sure the gap will still work but I let you handle that :D

You're right, my bad. It should be good now, the gap seems to be working properly. 
Screenshot 2024-08-29 at 11 28 56
Screenshot 2024-08-29 at 11 28 52
Screenshot 2024-08-29 at 11 28 45
Screenshot 2024-08-29 at 11 28 40
Screenshot 2024-08-29 at 11 28 36
Screenshot 2024-08-29 at 11 28 23

**Comment by lucasboilly** [comment]
It looks great, thanks @HichamELBSI!

**Review by simotae14 — APPROVED** [review]

**Review by alexandrebodin — APPROVED** [review]
LGTM 🚀

**Comment by alexandrebodin** [comment]
@HichamELBSI I think you need to add a changeset so this can trigger a new release ?

**Pull request merged**
