### PR TITLE
[enh] Initials customization

### PR DESCRIPTION
**Pull request by ronronscelestes**
## What

Allow background and textColor customization for `Initials` component 

### Snapshot

image

### CODE REVIEW

**Comment by gu-stav** [comment]
@ronronscelestes Where does that come from? Does that fix an issue or is this linked to another PR?

**Comment by ronronscelestes** [comment]
> @ronronscelestes Where does that come from? Does that fix an issue or is this linked to another PR?

it's a proposition
for the ML list view we create a brand new `Initials` like component just because it has a different background and text color

and other than a CMS issue, I think it would make sense to easily customize the colors of a text avatar with the DS color tokens - but it's just my opinion 🤷🏻‍♀️

**Comment by gu-stav** [comment]
>  for the ML list view we create a brand new Initials like component just because it has a different background and text color

Where do we render the initials in the list-view?

**Comment by ronronscelestes** [comment]
> Where do we render the initials in the list-view?

image

right now we are creating a custom component - that's why I thought it could make sense to allow some UI customization for `Initials` because it could be used there, only the color is different

**Review by gu-stav — APPROVED** [review]
That makes sense to me then!  🚀

**Review by joshuaellis — APPROVED** [review]

**Pull request merged**
