### PR TITLE
Rich text editor blocks icon

### PR DESCRIPTION
**Pull request by madhurisandbhor**
### Why is it needed?

To add "Blocks" type to the CTB, need Blocks icon.

### CODE REVIEW

**Review by gu-stav — COMMENTED** [review]
The current SVG is quite verbose. What do you think about simplifying it to:

```html
<svg width="34" height="25" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect x=".5" y="1" width="33" height="23" rx="2.5" fill="#EAF5FF" stroke="#B8E1FF"/>
  <path d="M18.9 9.83a1.04 1.04 0 1 0 0-2.09 1.04 1.04 0 0 0 0 2.09Z" fill="#0C75AF"/>
  <path d="M19.7 8.78a.8.8 0 0 1-.5.75.81.81 0 0 1-.92-.24.8.8 0 0 1 .75-1.3c.39.07.67.4.67.8 0 .3.49.3.49 0a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.28.47.83.7 1.36.6a1.3 1.3 0 0 0 1.03-1.26c0-.32-.48-.32-.49 0Zm-.8 4.71a1.04 1.04 0 1 0 0-2.09 1.04 1.04 0 0 0 0 2.09Z" fill="#0C75AF"/>
  <path d="M19.7 12.44a.8.8 0 0 1-.5.75.81.81 0 0 1-.92-.24.8.8 0 0 1 .75-1.3c.39.07.67.4.67.8 0 .3.49.3.49 0a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.28.47.83.7 1.36.6a1.3 1.3 0 0 0 1.03-1.26c0-.32-.48-.32-.49 0Zm-.8 4.81a1.04 1.04 0 1 0 0-2.09 1.04 1.04 0 0 0 0 2.09Z" fill="#0C75AF"/>
  <path d="M19.7 16.2a.8.8 0 0 1-.5.75.81.81 0 0 1-.92-.24.8.8 0 0 1 .75-1.3c.39.07.67.4.67.8 0 .3.49.3.49 0a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.28.47.83.7 1.36.6a1.3 1.3 0 0 0 1.03-1.26c0-.32-.48-.32-.49 0Zm-4.63-6.36a1.04 1.04 0 1 0 0-2.08 1.04 1.04 0 0 0 0 2.08Z" fill="#0C75AF"/>
  <path d="M15.88 8.8a.8.8 0 0 1-.52.75.81.81 0 0 1-.9-.24.8.8 0 0 1 .75-1.3c.39.07.66.4.67.79 0 .31.48.31.48 0a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.29.47.83.7 1.37.6a1.3 1.3 0 0 0 1.02-1.26c0-.31-.48-.31-.48 0Zm-.81 4.7a1.04 1.04 0 1 0 0-2.08 1.04 1.04 0 0 0 0 2.08Z" fill="#0C75AF"/>
  <path d="M15.88 12.46a.8.8 0 0 1-.52.75.81.81 0 0 1-.9-.24.8.8 0 1 1 1.42-.5c0 .3.48.3.48-.01a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.29.47.83.7 1.37.6a1.3 1.3 0 0 0 1.02-1.26c0-.31-.48-.31-.48 0Zm-.81 4.8a1.04 1.04 0 1 0 0-2.08 1.04 1.04 0 0 0 0 2.08Z" fill="#0C75AF"/>
  <path d="M15.88 16.22a.8.8 0 0 1-.52.75.81.81 0 0 1-.9-.24.8.8 0 1 1 1.42-.5c0 .3.48.3.48-.01a1.3 1.3 0 0 0-.87-1.22 1.29 1.29 0 0 0-1.52 1.88c.29.47.83.7 1.37.6a1.3 1.3 0 0 0 1.02-1.26c0-.31-.48-.31-.48 0Z" fill="#0C75AF"/>
</svg>
```

**Comment by joshuaellis** [comment]
I also don't think the rectangle needs a stroke and fill, imo it should just use a fill.

**Comment by madhurisandbhor** [comment]
> I also don't think the rectangle needs a stroke and fill, imo it should just use a fill.

I checked it, but both fill and stroke are required here.

**Review by remidej — APPROVED** [review]
LGTM, the source is concise and the icon matches the other CTB ones 👍

**Pull request merged**
